# Global parameters
[global]
    ldap server require strong auth = no
    tls enabled = no
    dns forwarder = 127.0.0.11
    netbios name = DC
    realm = NRSH13-HADOOP.COM
    server role = active directory domain controller
    workgroup = NRSH13-HADOOP
    idmap_ldb:use rfc2307 = yes

[sysvol]
    path = /var/lib/samba/sysvol
    read only = No

[netlogon]
    path = /var/lib/samba/sysvol/nrsh13-hadoop.com/scripts
    read only = No
